#!/bin/bash
set -e
# Helper script to build and/or install just one package out of this repository.
# Assumes that all the other packages it depends on have been installed already!

PROJECT="$1"
shift

COQFILE="_RocqProject.$PROJECT"
MAKEFILE="Makefile.package.$PROJECT"

if ! grep -E -q "^$PROJECT/" _RocqProject; then
    echo "No files in $PROJECT/ found in _RocqProject; this does not seem to be a valid project name."
    exit 1
fi

# Generate _RocqProject file and Makefile
rm -f "$COQFILE"
# Get the right "-Q" line.
grep -E "^-Q $PROJECT[ /]" _RocqProject >> "$COQFILE"
# Get everything until the first empty line except for the "-Q" lines.
sed -n '/./!q;p' _RocqProject | grep -E -v "^-Q " >> "$COQFILE"
# Get the files.
grep -E "^$PROJECT/" _RocqProject >> "$COQFILE"
# Now we can generate the makefile.
"${COQBIN}rocq" makefile -f "$COQFILE" -o "$MAKEFILE"

# Run build
make -f "$MAKEFILE" "$@"

# Cleanup
rm -f ".$MAKEFILE.d" "$MAKEFILE"*
